queue:
  name: Hosted VS2017
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: "-no_logo"
    modifyEnvironment: "true"

- powershell: |
    .\build.ps1 -target ci    
  displayName: Build
  env:
    TOKEN: $(System.AccessToken)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "artifacts/build"
    ArtifactName: "build"
    ArtifactType: "Container"
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "artifacts/packages"
    ArtifactName: "packages"
    ArtifactType: "Container"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "artifacts/test"
    ArtifactName: "test"
    ArtifactType: "Container"